
POST http://localhost:3031/videos
Content-Type: application/json

{
    "title": "video node2",
    "description":  "Esse é o primeiro video mano",
    "duration": 100
}

###
GET http://localhost:3031/videos

###

PUT http://localhost:3031/videos/
Content-Type: application/json

{
    "title": "Video 10",
    "description":  "ola mundo",
    "duration": 100
}

###

DELETE http://localhost:3031/videos/