
POST https://node-server-q4zo.onrender.com/videos
Content-Type: application/json

{
    "title": "video ",
    "description":  "Esse é o primeiro video mano",
    "duration": 100
}

###
GET https://node-server-q4zo.onrender.com/videos

###

PUT https://node-server-q4zo.onrender.com/videos/ab53b7a3-031a-443d-be3d-7691bde8069d
Content-Type: application/json

{
    "title": "Video novo",
    "description":  "ola mundo",
    "duration": 100
}

###

DELETE https://node-server-q4zo.onrender.com/videos/1a7496ec-9675-4288-97ec-6cf323c2bcae